const INIT_STARDUX = 'INIT_STARDUX';
const CLR_STARDUX = 'CLR_STARDUX';
const CHG_PROPS = 'CHG_PROPS';
const OVERLAY_PROPS = 'OVERLAY_PROPS';

export default {
  INIT_STARDUX,
  CLR_STARDUX,
  CHG_PROPS,
  OVERLAY_PROPS
};
