const INIT_STYLING = 'INIT_STYLING';
const CLR_STYLING = 'CLR_STYLING';
const INIT_THEMEMAP = 'INIT_THEMEMAP';
const CLR_THEMEMAP = 'CLR_THEMEMAP';

export default {
  INIT_STYLING,
  CLR_STYLING,
  INIT_THEMEMAP,
  CLR_THEMEMAP
};
